import { chromium } from '/home/alv/projects/makefx/node_modules/.pnpm/playwright@1.62.1/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
await page.goto((process.env.BASE || 'http://localhost:8123/index.html') + '?t=15&paused=1');
await page.waitForFunction(() => window.__room && window.__room.frames > 5);
const tile = page.getByRole('button', { name: /Add Cardboard box/ });
const b = await tile.boundingBox();
const [tx, ty] = await page.evaluate(() => window.__room.project([0.6, 0, 0.9]));
await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2);
await page.mouse.down();
for (let i = 1; i <= 15; i++) await page.mouse.move(b.x + (tx - b.x) * i / 15, b.y + (ty - b.y) * i / 15);
await page.mouse.up();
await page.waitForTimeout(1500);
console.log('box at', await page.evaluate(() => { const p = window.__room.props.find((q) => q.type === 'box'); return p && [p.item.x.toFixed(2), p.item.z.toFixed(2)]; }), 'target 0.60,0.90');
await page.getByRole('button', { name: /Add Candle/ }).click();
await page.waitForTimeout(800);
console.log('candle', await page.evaluate(() => !!window.__room.props.find((q) => q.type === 'candle')));
await page.getByRole('button', { name: 'Remove Cardboard box' }).click();
console.log('box removed', await page.evaluate(() => !window.__room.props.find((q) => q.type === 'box')));
console.log(errs.join('\n') || 'no errors');
await browser.close();
